# Generated by Django 5.2.4 on 2025-07-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerne',
            new_name='Genre',
        ),
    ]
