# Generated by Django 5.2.4 on 2025-07-16 02:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (
                    ("can_mark_returned", "Set book as returned"),
                    ("can_renew", "Renew a book"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular"
                " book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
